name: Deploy via FTP - Organize suas Finanças

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy para Locaweb
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Deploy via FTP (Locaweb)
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "dist"
          remoteDir: "/public_html/"
